import './globals.css';
import { Inter } from 'next/font/google';
import { Toaster } from "@/components/ui/sonner"
import Providers from '@/components/Provider'

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Canvas Editor',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
         <Providers>
        {children}
        <Toaster
  position="top-right"
  theme="light"
  toastOptions={{
    style: {
      background: "linear-gradient(135deg, #7e22ce, #a855f7)",
      color: "white",
      borderRadius: "10px",
      boxShadow: "0 4px 14px rgba(0,0,0,0.2)",
    },
    duration: 4000, // Optional: sets how long the toast shows
  }}
/>
</Providers>
      </body>
    </html>
  );
}


